# Generated by Django 5.2 on 2025-05-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslog',
            options={'ordering': ['-created_at'], 'permissions': [('can_export', 'Can export access logs')], 'verbose_name': 'access log', 'verbose_name_plural': 'access logs'},
        ),
    ]
